export const STATE = {
    ST: null,
    FIELD: null,
    FIGHTER: null,
    SHOT: null,
    METEOR: null,
    CONTROLLERS: null,
    speed: 5,
    command: '',
    shotCommand: '',
    isFlashLoaded: true,
    isFlashLoading: true,
    flashProgress: document.getElementById('flash-progres'),
    direction: "up",
}