export const STATE = {
    direction: "up",
    currDirection: { x: 0, y: -1 },
    rotateDegree: 0,
    speed: 5,
    flash: 150,
    flashProgress: document.getElementById('flash-progres'),
    isFlashLoaded: true,
    isFlashLoading: true,
    st: null,
    field: null,
    fighter: null,
    shot: null,
    meteor: null,
    controllers: null,
}